### ISSUE TITLE
molecular-fluorescence-spectroscopy_introduction-to-the-fluorescence-spectroscopy-principle_procedure

### ISSUE THREAD

**Issue by gayatripurigilla** [virtual-labs/molecular-florescence-spectroscopy-iiith#1]
Defect description: procedure does not contain any data. steps to reproduce the issue : 1)after logging in vlabs. 2) selecting iiit-hyderabad institute available in the participating institute in the left corner of the webpage. 3) under virtual labs at iiith section, we select molecular-fluoroscence spectroscopy lab.4)select experiments. 5) select introduction to the fluoroscence spectroscopy. 6) select procedure. 6)manual. expected result: procedure for given experiment should be displayed. actual result: it displays "procedure is under construction" i.e there is no content.screenshot : ![molecularfluoroscence1](https://gitlab.com/godaaditya24/virtual-labs-internship-adityabharadwaj/uploads/058f08e76ce4ebc80856fee1840ab30d/MolecularFluoroscence1.JPG)

**Comment by kurasaiteja** [comment]
same issue #4
